Design/#109
CAUCSE/CAUSW_frontend pull request #110
Opened 2024-03-21 10:49 UTC by selfishAltruism

🚩 관련 이슈
resolve #109

📋 PR Checklist

- 동아리 설명 카드 크기 조절
- 동아리 설명 카드 대표 이미지 배경색 조정
- 동아리 카드 라우터 에러 해결

📌 유의사항

- 디자인 팀 결과물 나온 이후 다시 진행 예정

✅ 테스트 결과

![image](https://github.com/CAUCSE/CAUSW_frontend/assets/135580919/0754d8ec-3017-425e-b329-32c414be7f0e)

2024-03-21 13:11 UTC, lee0jae330 commented
고생하셨습니다

2024-03-21 13:59 UTC, omjinLTS commented
LGTM

2024-03-21 14:06 UTC, omjinLTS requested changes
오래걸리는거면 패스

2024-03-21 14:06 UTC, omjinLTS commented on src/pages/circle/home/CircleHomePage.tsx
> +            ListComponent={!isMobile ? Circle.WebSlider : Circle.Slider}
이거 ! 빼고 앞뒤 순서 바꾸는게 어떰
그리고 차후여도되고 WebSlider / Slider 말고 WebSlider / MobileSlider로 ㄱㄴ?

2024-03-21 14:06 UTC, omjinLTS commented on src/pages/circle/home/CircleHomePage.tsx
> +            ListComponent={!isMobile ? Circle.WebSlider : Circle.Slider}
나중에라도 헷갈릴거같애서

2024-03-21 14:31 UTC, Ontheway-01 commented
굿입니다~

2024-03-22 04:29 UTC, selfishAltruism commented on src/pages/circle/home/CircleHomePage.tsx
> +            ListComponent={!isMobile ? Circle.WebSlider : Circle.Slider}
오늘 중으로 해볼게유

2024-03-22 04:54 UTC, selfishAltruism commented on src/pages/circle/home/CircleHomePage.tsx
> +            ListComponent={!isMobile ? Circle.WebSlider : Circle.Slider}
확인 바랍니다 :)

2024-03-22 05:01 UTC, omjinLTS approved these changes
LGTM

2024-03-22 05:11 UTC, merged